const dimensions=[
{key:"audace",label:"AUDACE",sign:"Bélier",questions:["Quand j'ai une idée, je suis capable de la tester sans attendre qu'elle soit parfaitement aboutie.","Je prends des décisions rapidement sans avoir besoin de demander l'avis de plusieurs personnes pour me rassurer.","J'ose lancer une offre, un projet ou une nouvelle idée même si je ne sais pas encore exactement comment elle sera reçue.","Je sais saisir une opportunité sans laisser la peur ou le doute me faire reculer.","Je passe facilement de « j'aimerais faire ça » à « je le fais »."],result:{title:"Tu sais peut-être quoi faire. Mais au moment d’y aller… tu freines.",body:"Tu peux avoir de très bonnes idées, savoir exactement ce que tu devrais lancer ou quelle décision tu devrais prendre… et quand même attendre. Tu réfléchis encore. Tu demandes un avis. Tu veux être sûre. Tu repousses le lancement. Tu attends le bon moment. Et parfois, tu appelles ça de la prudence alors qu’en réalité, tu essaies surtout d’éviter le risque de te tromper.",behind:"Peur de l’échec, peur de faire le mauvais choix, besoin de validation, difficulté à faire confiance à ses décisions.",liberated:"Tu décides plus vite, tu testes, tu ajustes et surtout… tu arrêtes d’avoir besoin d’être certaine pour avancer."}},
{key:"prosperite",label:"PROSPÉRITÉ",sign:"Taureau",questions:["Je suis à l'aise avec le prix de mes offres et je n'éprouve pas le besoin de le justifier.","Je peux recevoir beaucoup plus d'argent qu'aujourd'hui sans avoir l'impression que je vais devoir travailler beaucoup plus.","Je parle d'argent, de prix et de chiffre d'affaires sans gêne particulière.","Je me sens capable de construire une activité financièrement stable, même lorsque mes revenus ne sont pas garantis d'un mois sur l'autre.","Lorsque mon entreprise gagne davantage d'argent, je sais le conserver, le gérer et l'utiliser sans ressentir le besoin de le dépenser immédiatement."],result:{title:"Tu peux vouloir gagner plus… et ne pas être complètement à l’aise avec ce que ça implique.",body:"Augmenter tes prix. Annoncer un tarif sans te justifier. Recevoir beaucoup d’argent pour quelque chose qui ne t’a pas demandé trois semaines de travail. Sur le papier, tu veux évidemment que ton business gagne plus. Mais dans la réalité, recevoir davantage peut venir toucher beaucoup plus de choses que ton compte bancaire.",behind:"Valeur personnelle associée au travail fourni, peur de manquer, culpabilité à recevoir, croyance qu’il faut travailler dur pour mériter beaucoup.",liberated:"L’argent arrête d’être quelque chose qu’il faut constamment mériter. Tu peux assumer tes prix, recevoir davantage et surtout laisser cet argent rester dans ton entreprise."}},
{key:"communication",label:"COMMUNICATION",sign:"Gémeaux",questions:["Je peux expliquer en quelques phrases ce que je fais et pour qui je le fais.","Je trouve facilement des sujets de contenu en lien avec mon expertise.","J'arrive à exprimer mes idées avec mes propres mots sans chercher constamment la formulation parfaite.","Je sais adapter ma façon de communiquer pour que mon audience comprenne facilement mon message.","Je publie ce que j'ai réellement envie de dire plutôt que ce que je pense devoir dire pour plaire à l'algorithme."],result:{title:"Tu sais ce que tu fais. Le problème, c’est peut-être de réussir à l’expliquer.",body:"Tu peux avoir énormément de choses à dire… et passer pourtant un temps fou devant une page blanche. Parce que tu veux trouver le bon angle. La bonne formulation. Le bon contenu. Ou parce que ton expertise est tellement évidente pour toi que tu ne sais plus comment l’expliquer simplement.",behind:"Peur d’être mal comprise, peur de dire une bêtise, surmentalisation, difficulté à simplifier ou à faire confiance à sa propre voix.",liberated:"Ton message devient plus clair, tes contenus plus naturels et ton audience comprend beaucoup plus rapidement pourquoi ton travail peut l’aider."}},
{key:"intuition",label:"INTUITION",sign:"Cancer",questions:["Je sais reconnaître la différence entre une décision qui me fait peur et une décision qui n'est réellement pas juste pour moi.","Je peux prendre une décision professionnelle en me fiant à mon intuition même si je n'ai pas encore toutes les preuves qu'elle fonctionnera.","Je sais remettre en question une méthode business recommandée par tout le monde lorsqu'elle ne me correspond pas.","Mon entreprise respecte suffisamment mes besoins, mon énergie et ma vie personnelle pour que je puisse m'y sentir bien durablement.","Lorsque mon activité traverse une période d'incertitude, je parviens à garder suffisamment de sécurité intérieure pour ne pas remettre tout mon business en question."],result:{title:"À force d’écouter tous les conseils business, est-ce que tu t’entends encore toi ?",body:"La méthode dit de faire ça. Ton mentor te conseille autre chose. Sur Instagram, tout le monde semble avoir trouvé LA stratégie qui fonctionne. Et toi, au milieu de tout ça ? Tu peux finir par construire un business techniquement cohérent… dans lequel tu ne te sens absolument pas bien.",behind:"Manque de sécurité intérieure, peur de faire différemment, besoin d’être rassurée, difficulté à reconnaître ses propres besoins.",liberated:"Tu utilises les stratégies comme des outils et non comme des règles. Tu sais écouter les conseils sans te perdre dedans et construire une entreprise dans laquelle tu peux réellement respirer."}},
{key:"visibilite",label:"VISIBILITÉ",sign:"Lion",questions:["Je suis à l'aise lorsque mon visage, mon nom ou ma personnalité deviennent associés à mon entreprise.","Je peux parler de mes réussites et de mes compétences sans avoir peur de paraître prétentieuse.","J'ose prendre publiquement position même lorsque je sais que certaines personnes ne seront pas d'accord.","Les critiques ou le regard des autres ne m'empêchent pas de publier ce que j'ai réellement envie de dire.","Je me sens légitime à devenir une personne reconnue dans mon domaine."],result:{title:"Tu veux être connue… mais est-ce que tu acceptes vraiment d’être vue ?",body:"Tu peux vouloir plus de clientes, plus d’abonnés, plus d’opportunités… tout en paniquant intérieurement dès qu’un contenu commence réellement à attirer l’attention. Alors tu lisses. Tu arrondis. Tu évites certaines prises de position.",behind:"Peur du jugement, du rejet, de la critique, d’être trop, de déranger ou de prendre trop de place.",liberated:"Tu n’essaies plus d’être visible sans être remarquée. Tu incarnes ta marque, tu prends position et tu laisses enfin les bonnes personnes te reconnaître."}},
{key:"expertise",label:"EXPERTISE",sign:"Vierge",questions:["Je me sens suffisamment compétente pour facturer mon expertise sans avoir besoin d'une formation supplémentaire pour me rassurer.","Je peux proposer un travail de grande qualité sans chercher à ce que tout soit parfait.","Je sais clairement ce que je fais mieux ou différemment dans mon domaine.","Je peux considérer qu'un travail est terminé et le montrer même si je vois encore des choses que je pourrais améliorer.","Je fais confiance à mon expérience autant qu'à mes diplômes, certifications ou connaissances théoriques."],result:{title:"Combien faudra-t-il encore apprendre avant que tu te considères enfin suffisamment compétente ?",body:"Une formation supplémentaire. Une certification. Encore quelques clientes. Encore un peu d’expérience. Et peut-être qu’après ça, tu te sentiras légitime. Ou pas.",behind:"Perfectionnisme, syndrome de l’imposteur, peur de l’erreur, valeur personnelle associée à la performance.",liberated:"Tu continues à progresser, évidemment. Mais tu n’attends plus d’être irréprochable pour reconnaître ton expertise et la faire payer à sa juste valeur."}},
{key:"relation",label:"RELATION",sign:"Balance",questions:["Je peux proposer mon offre à quelqu'un sans avoir peur de le déranger ou de lui mettre la pression.","Je sais poser une limite à un client même si je sais qu'il risque d'être déçu.","Je suis à l'aise pour créer des partenariats, collaborations ou recommandations avec d'autres entrepreneurs.","Je peux négocier mes conditions ou défendre mes intérêts sans craindre d'abîmer la relation.","Je sais entretenir une bonne relation client sans devenir disponible en permanence."],result:{title:"Être une bonne professionnelle ne veut pas dire dire oui à tout le monde.",body:"Oui à la cliente qui écrit le dimanche. Oui à la demande qui n’était pas prévue. Oui à la remise parce qu’elle hésite. Oui au partenariat qui ne t’emballe pas vraiment parce que tu ne veux pas vexer.",behind:"Peur de déplaire, du conflit, du rejet, besoin d’être appréciée, difficulté à poser une limite.",liberated:"Tu peux vendre, négocier, collaborer et prendre soin de tes clientes sans te sacrifier pour maintenir la relation."}},
{key:"puissance",label:"PUISSANCE",sign:"Scorpion",questions:["Je peux imaginer gagner beaucoup plus d'argent sans ressentir de gêne vis-à-vis des personnes qui gagnent moins que moi.","Je suis capable d'abandonner une offre, une façon de travailler ou une identité professionnelle qui ne correspond plus à la personne que je deviens.","Je peux prendre une décision difficile lorsqu'elle est nécessaire à la croissance de mon entreprise.","L'idée d'avoir davantage d'influence, d'argent ou de responsabilités m'attire davantage qu'elle ne m'effraie.","Lorsqu'une période professionnelle se termine ou qu'un projet échoue, je sais reconstruire plutôt que m'accrocher longtemps à ce qui ne fonctionne plus."],result:{title:"Et si ton prochain plafond n’était pas la peur d’échouer… mais celle de réussir beaucoup plus grand ?",body:"Plus d’argent. Plus de clientes. Plus d’influence. Plus de responsabilités. Ça peut faire rêver. Et ça peut aussi foutre une sacrée trouille.",behind:"Peur de perdre, peur du pouvoir, loyautés, culpabilité à réussir, besoin de contrôle.",liberated:"Tu n’as plus besoin de rester petite pour rester en sécurité. Tu peux transformer ton entreprise sans t’accrocher à ce qu’elle était hier."}},
{key:"vision",label:"VISION",sign:"Sagittaire",questions:["Je sais à quoi j'aimerais que mon entreprise ressemble dans trois à cinq ans.","J'ai une vision suffisamment grande pour m'enthousiasmer, même si je ne sais pas encore comment l'atteindre.","Je m'autorise des ambitions qui dépassent largement ce que j'ai déjà accompli.","Mes décisions actuelles sont cohérentes avec l'entreprise que je veux construire à long terme.","Lorsque je pense à mon avenir professionnel, je réfléchis au-delà de mon prochain lancement ou de mon prochain objectif de chiffre d'affaires."],result:{title:"Tu veux faire grandir ton business. D’accord. Mais jusqu’où ?",body:"Parce que avoir plus de clientes ou gagner plus n’est pas forcément une vision. Une vision, c’est savoir ce que tu veux réellement construire au-delà du prochain mois, du prochain lancement ou du prochain objectif de chiffre d’affaires.",behind:"Peur de rêver trop grand, difficulté à se projeter, objectifs construits à partir de ce qui semble raisonnable plutôt que de ce qui est réellement désiré.",liberated:"Tu ne construis plus seulement ton prochain mois. Tu sais où tu veux emmener ton entreprise et tes décisions commencent à servir cette direction."}},
{key:"leadership",label:"LEADERSHIP",sign:"Capricorne",questions:["Je me considère réellement comme la dirigeante de mon entreprise, et pas simplement comme quelqu'un qui exerce son métier à son compte.","Je sais définir mes priorités sans laisser les urgences décider constamment à ma place.","Je tiens mes décisions et mes engagements professionnels même lorsque ma motivation redescend.","Je suis capable de déléguer ou d'envisager de déléguer sans penser que tout doit forcément passer par moi.","Je prends mes décisions en fonction de ce dont mon entreprise a besoin pour grandir, et pas uniquement de ce qui est confortable aujourd'hui."],result:{title:"Est-ce que tu diriges ton entreprise… ou est-ce que tu as simplement créé ton propre emploi ?",body:"On peut être entrepreneure et passer ses journées à exécuter. Répondre. Produire. Publier. Livrer. Gérer les urgences. Et recommencer demain.",behind:"Difficulté à déléguer, besoin de contrôle, peur de prendre des responsabilités plus grandes, difficulté à prioriser ou à tenir un cadre.",liberated:"Tu ne te demandes plus uniquement ce que tu dois faire aujourd’hui. Tu commences à prendre les décisions de la dirigeante de l’entreprise que tu veux construire."}},
{key:"impact",label:"IMPACT",sign:"Verseau",questions:["Je sais ce qui rend mon approche réellement différente de celles des autres personnes de mon secteur.","J'ose créer ou proposer quelque chose même lorsque cela ne ressemble pas à ce qui fonctionne déjà sur mon marché.","Je sais quelle idée, quelle conviction ou quel changement j'aimerais faire émerger grâce à mon entreprise.","Je crée du contenu qui donne envie aux personnes de se rassembler autour de mes idées, et pas uniquement d'acheter mes offres.","Je réfléchis à la manière dont mon entreprise pourrait toucher davantage de personnes sans que tout repose nécessairement sur moi individuellement."],result:{title:"Si on enlève tes offres… qu’est-ce que ton entreprise défend ?",body:"Une marque forte ne rassemble pas uniquement autour de ce qu’elle vend. Elle porte une idée. Une façon différente de voir les choses. Quelque chose auquel les gens ont envie d’appartenir.",behind:"Peur d’être différente, tendance à reproduire les codes de son marché, peur de polariser, difficulté à assumer une vision collective.",liberated:"Tu ne cherches plus seulement une audience. Tu crées une communauté autour d’une idée suffisamment forte pour dépasser tes offres."}},
{key:"creativite",label:"CRÉATIVITÉ",sign:"Poissons",questions:["Je me donne la permission de suivre une idée créative même lorsqu'elle ne correspond pas à ce qui se fait habituellement dans mon secteur.","Mon entreprise possède un univers, une atmosphère ou une identité que l'on peut reconnaître au-delà de mes offres.","Je sais transformer une inspiration ou une idée abstraite en quelque chose de concret que je peux proposer à mon audience.","Je laisse suffisamment d'espace dans mon activité pour créer plutôt que d'être constamment dans l'exécution.","Je fais confiance à mon imagination pour inventer de nouvelles offres, expériences ou façons de transmettre."],result:{title:"Est-ce que tu crées encore… ou est-ce que tu passes ton temps à regarder ce qui fonctionne chez les autres ?",body:"À force de chercher les bonnes pratiques, les tendances, les formats qui performent et ce que l’algorithme préfère… on peut finir avec un business parfaitement optimisé. Et complètement sans âme.",behind:"Peur que ses idées ne fonctionnent pas, comparaison, besoin de validation extérieure, difficulté à donner de la valeur à ce qui vient naturellement.",liberated:"Tu recommences à inventer. Tes offres, ton univers et ta façon de transmettre deviennent plus reconnaissables parce qu’ils viennent réellement de toi."}}
];

const flat=dimensions.flatMap(d=>d.questions.map(q=>({d,q})));
const answersScale=[["Pas du tout",1],["Plutôt non",2],["Mitigé",3],["Plutôt oui",4],["Complètement",5]];
let i=0; const responses=[]; let lead={};

const leadForm=document.getElementById("lead-form");
const quiz=document.getElementById("quiz");
const results=document.getElementById("results");

leadForm.addEventListener("submit",async e=>{
 e.preventDefault();
 const fd=new FormData(leadForm);
 lead={prenom:fd.get("prenom"),email:fd.get("email")};
 await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(fd).toString()});
 document.querySelector(".hero").classList.add("hidden"); quiz.classList.remove("hidden"); renderQuestion(); window.scrollTo({top:0,behavior:"smooth"});
});

function renderQuestion(){
 const item=flat[i]; document.getElementById("progress-label").textContent=`Question ${i+1} sur ${flat.length}`;
 document.getElementById("progress-bar").style.width=`${(i/flat.length)*100}%`;
 document.getElementById("dimension-label").textContent=item.d.label;
 document.getElementById("question-text").textContent=item.q;
 const a=document.getElementById("answers"); a.innerHTML="";
 answersScale.forEach(([label,val])=>{const b=document.createElement("button");b.type="button";b.className="answer-btn";b.textContent=label;b.onclick=()=>{responses.push({key:item.d.key,value:val});i++; if(i<flat.length)renderQuestion(); else finish();};a.appendChild(b);});
}

function calcScores(){
 const out={};
 dimensions.forEach(d=>{const vals=responses.filter(r=>r.key===d.key).map(r=>r.value); const avg=vals.reduce((a,b)=>a+b,0)/vals.length; out[d.key]=Math.round(((avg-1)/4)*100);});
 return out;
}

async function finish(){
 const scores=calcScores(); quiz.classList.add("hidden");
 const sorted=[...dimensions].sort((a,b)=>scores[a.key]-scores[b.key]); const top3=sorted.slice(0,3);
 const fd=new URLSearchParams();
 fd.append("form-name","diagnostic-results"); fd.append("prenom",lead.prenom); fd.append("email",lead.email);
 dimensions.forEach(d=>fd.append("score_"+d.key,String(scores[d.key])));
 fd.append("priorite_1",top3[0].label); fd.append("priorite_2",top3[1].label); fd.append("priorite_3",top3[2].label);
 await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:fd.toString()}).catch(()=>{});
 renderResults(scores,top3); window.scrollTo({top:0,behavior:"smooth"});
}

function renderResults(scores,top3){
 results.classList.remove("hidden");
 results.innerHTML=`
 <div class="results-head"><div class="eyebrow">TES RÉSULTATS</div><h1>TU VOIS LE PROBLÈME MAINTENANT ?</h1>
 <p><strong>Tu n’as jamais manqué de stratégie.</strong></p>
 <p>Tu savais déjà qu’il fallait te montrer, vendre, parler de ton offre, assumer tes prix, prendre des décisions et arrêter de jouer petit. Le problème, c’est que savoir quoi faire n’a jamais suffi à être capable de le faire.</p></div>
 <div class="scores-grid">${dimensions.map(d=>`<div class="score-card ${top3.some(p=>p.key===d.key)?"score-card--priority":""}"><span>${d.label}</span><strong>${scores[d.key]} %</strong>${top3.some(p=>p.key===d.key)?'<em>À travailler en priorité</em>':""}</div>`).join("")}</div>
 <h2>VOICI LES 3 ENDROITS OÙ TON BUSINESS TE DEMANDE AUJOURD’HUI DE SHIFTER.</h2>
 <div class="priority-list">${top3.map((d,idx)=>`<article class="result-card"><div class="score-badge">#${idx+1} — ${d.label} · ${scores[d.key]} %</div><h3>${d.result.title}</h3><p>${d.result.body}</p><h4>Ce qui peut se jouer derrière</h4><p>${d.result.behind}</p><h4>Quand cette dimension se libère</h4><p>${d.result.liberated}</p></article>`).join("")}</div>
 <section class="about-aurelia">
   <div class="about-copy">
     <div class="eyebrow">JE SUIS AURÉLIA</div>
     <h2>Et si on construisait les business complètement à l’envers ?</h2>
     <p>Quand on crée son entreprise, le premier réflexe, c’est souvent de prendre une formation business. On apprend à construire une offre, définir une stratégie, communiquer, vendre, créer du contenu…</p>
     <p><strong>Mais on oublie généralement de commencer par la base : devenir l’entrepreneure capable de porter tout ça.</strong></p>
     <p>Alors on essaie d’appliquer des stratégies avec une identité qui, elle, n’est pas encore à l’aise avec le fait de se montrer, vendre, recevoir davantage d’argent, prendre des décisions, poser des limites ou voir beaucoup plus grand.</p>
     <p>Et forcément, ça pousse. Ça force. On essaie de faire rentrer la stratégie dans une identité qui n’est pas encore prête à la soutenir.</p>
     <p><strong>Pour moi, l’ordre devrait être exactement l’inverse.</strong></p>
     <p>On travaille d’abord sur ton identité d’entrepreneure : ce que tu t’autorises à faire, à recevoir, à montrer, à assumer et à devenir. Et ensuite, la stratégie arrête d’être quelque chose que tu dois te forcer à appliquer. Elle devient beaucoup plus naturelle, fluide et cohérente avec qui tu es.</p>
     <p>C’est précisément pour ça que j’ai créé ALKÉMIA et que je travaille aujourd’hui sur la <strong>reprogrammation neuro-identitaire</strong>.</p>
   </div>
 </section>
 <div class="offers">
   <article class="offer-card primary"><div class="eyebrow">SUCCESS</div><h2>Ton business ne pourra pas aller plus loin que l’identité avec laquelle tu essaies de le construire.</h2><p>SUCCESS sera un accompagnement entièrement consacré à <strong>ton identité entrepreneuriale</strong>. SUCCESS n’est pas encore ouvert, mais tu peux t’inscrire dès maintenant sur la liste prioritaire.</p><button id="success-btn">JE M’INSCRIS SUR LA LISTE PRIORITAIRE SUCCESS →</button></article>
   <article class="offer-card"><div class="eyebrow">LES CODES D’ALKÉMIA</div><h3>Tu veux commencer seule sur une énergie précise ?</h3><p>Tu peux commencer à travailler directement sur l’énergie zodiacale qui correspond à ce que ton diagnostic vient de mettre en lumière.</p><a class="cta" href="https://lescodesdalkemia.netlify.app/" target="_blank" rel="noopener">DÉCOUVRIR LES CODES D’ALKÉMIA →</a></article>
   <article class="offer-card"><div class="eyebrow">ORIGINE</div><h3>Tu sens que ce qui se joue dépasse largement ton business ?</h3><p>ORIGINE est mon accompagnement individuel pour aller travailler en profondeur sur tes programmes inconscients, à partir de ta propre carte du ciel. Ici, on travaille sur toi à 360°.</p><a class="cta" href="https://alkemia.netlify.app/origine" target="_blank" rel="noopener">DÉCOUVRIR ORIGINE →</a></article>
 </div>`;
 document.getElementById("success-btn").addEventListener("click",joinSuccess);
}

async function joinSuccess(){
 const fd=new URLSearchParams(); fd.append("form-name","success-priority"); fd.append("prenom",lead.prenom); fd.append("email",lead.email); fd.append("interet_success","oui");
 await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:fd.toString()});
 const b=document.getElementById("success-btn"); b.textContent="C’EST BON, TU ES SUR LA LISTE PRIORITAIRE ✓"; b.disabled=true;
}
